mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^project/', include('project.urls', namespace="project")),
    url(r'^admin/', include(admin.site.urls)),
]

mysite/project/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='project/index.html'), name="Home"),
    #url(r'^login/', TemplateView.as_view(template_name='project/login.html'), name="Login"),
    url(r'^login/', views.Login, name="Login"),
    url(r'^logout/', views.Logout, name="Logout"),
    url(r'^register/', views.Register, name="Register"),
    url(r'^userprofile/(?P<pk>[0-9]+)', views.UserView.as_view(), name="UserProfile"),
    url(r'^jumps/', views.JumpsView.as_view(), name="Jumps"),
    url(r'^jump/(?P<pk>[0-9]+)', views.JumpView.as_view(), name="Jump"),
    url(r'^jump/edit/(?P<pk>[0-9]+)', views.EditJump, name="EditJump"),
]

mysite/project/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Picture(models.Model):
	URL = models.CharField(max_length=1000)
	Verified = models.BooleanField()

class Dropzone(models.Model):
	DropzoneName = models.CharField(max_length=50)
	TheDescription = models.CharField(max_length=1000)
	pictureID = models.ForeignKey(Picture, blank=True, null=True)

class EventType(models.Model):
	EventTypeName = models.CharField(max_length=50)
	pictureID = models.ForeignKey(Picture, blank=True, null=True)

class Event(models.Model):
	EventTypeID = models.ForeignKey(EventType)
	DropzoneID = models.ForeignKey(Dropzone)
	EventName = models.CharField(max_length=50)
	TheDescription = models.CharField(max_length=1000)
	StartDate = models.DateTimeField('start date')
	EndDate = models.DateTimeField('end date')
	Spaces = models.IntegerField(default=0)

class JumpType(models.Model):
	JumpTypeName = models.CharField(max_length=50)
	pictureID = models.ForeignKey(Picture, blank=True, null=True)

class VideoResource(models.Model):
	URL = models.CharField(max_length=1000)
	Verified = models.BooleanField()

class Jump(models.Model):
	JumpTypeID = models.ForeignKey(JumpType)
	VideoResourceID = models.ForeignKey(VideoResource, blank=True, null=True)
	ShortDescription = models.CharField(max_length=100)
	TheDescription = models.CharField(max_length=1000)
	Notes = models.CharField(max_length=1000)
	JumpDate = models.DateTimeField('jump date')

class ProductType(models.Model):
	ProductName = models.CharField(max_length=50)
	TheDescription = models.CharField(max_length=1000)
	PictureID = models.ForeignKey(Picture, blank=True, null=True)

class Product(models.Model):
	ProductName = models.CharField(max_length=50)
	ProductTypeID = models.ForeignKey(ProductType)

class UserBookingEventProduct(models.Model):
	EventID = models.ForeignKey(Event)
	ProductID = models.ForeignKey(Product)

class UserProfile(models.Model):
	UserID = models.OneToOneField(User, unique=True)
	JumpNumber = models.IntegerField()

class UserBooking(models.Model):
	EventProductID = models.ForeignKey(UserBookingEventProduct)
	UserProfileID = models.ForeignKey(UserProfile)
	BookingDate = models.DateTimeField('booking date')

class UserJump(models.Model):
	UserProfileID = models.ForeignKey(UserProfile)
	JumpID = models.ForeignKey(Jump)
	JumpNumber = models.IntegerField()
	isOwner = models.BooleanField()

mysite/project/forms.py
from django import forms
from .models import Jump

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, error_messages={'required': 'Please enter a username.'})
    password = forms.CharField(widget=forms.PasswordInput, label='Password', error_messages={'required': 'Please enter your password.'})
    remember = forms.BooleanField(required=False)

class RegisterForm(forms.Form):
	username = forms.CharField(label='Username', max_length=100, error_messages={'required': 'Please enter a username.'})
	password = forms.CharField(widget=forms.PasswordInput, label='Password', error_messages={'required': 'Please enter your password.'})
	email = forms.EmailField(error_messages={'required': 'Please enter your email.'})
	firstname = forms.CharField(label='First Name', max_length=100, error_messages={'required': 'Please enter your first name.'})
	lastname = forms.CharField(label='Last Name', max_length=100, error_messages={'required': 'Please enter your last name.'})
	jumpnumber = forms.IntegerField(error_messages={'required': 'Please enter your jump number.'})

class PostForm(forms.ModelForm):
    class Meta:
        model = Jump
        # exclude = ['author', 'updated', 'created', ]
        fields = ['TheDescription', 'Notes']
        #widgets = {
        #    'text': forms.TextInput(
        #        attrs={'id': 'post-text', 'required': True, 'placeholder': 'Say something...'}
        #    ),
        #}

mysite/project/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

import json

from .models import Jump, UserProfile, Dropzone
from .forms import LoginForm, RegisterForm

# Create your views here.
class IndexView(generic.ListView):
	template_name = 'project/index.html'

	def get_queryset(self):
		return Dropzone.objects.all()

class UserView(generic.DetailView):
	template_name = 'project/user.html'
	model = UserProfile

class JumpsView(generic.ListView):
	template_name = 'project/jumps.html'
	context_object_name = 'jumps'

	def get_queryset(self):
		return Jump.objects.all()

class JumpView(generic.DetailView):
	template_name = 'project/jump.html'
	model = Jump

def EditJump(request, pk):
	if request.method == 'POST':
		p = get_object_or_404(Jump, pk=pk)
		p.TheDescription = request.POST.get("Description")
		p.Notes = request.POST.get("Notes")
		p.save()
		response_data = {}

		response_data["TheDescription"] = p.TheDescription
		response_data["Notes"] = p.Notes
		return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
	else:
		return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )

def Login(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return HttpResponseRedirect('/project/')
				else:
					form.add_error(None, "Your account has been disabled.")
			else:
				form.add_error(None, "Invalid username or password.")
	else:
		form = LoginForm()

	return render(request, 'project/login.html', {'form': form})

def Logout(request):
    logout(request)
    return HttpResponseRedirect('/project/')

def Register(request):
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid():
			user = User.objects.create_user(request.POST['username'], request.POST['email'], request.POST['password'])
			user.first_name = request.POST['firstname']
			user.last_name = request.POST['lastname']
			user.Save()
			userProfile = UserProfile.objects.create(UserID=user, JumpNumber=request.POST['jumpnumber'])
			if user is not None:
				if userProfile is not None:
					return HttpResponseRedirect('/project/')
				else:
					form.add_error(None, "Error creating your User Profile")
			else:
				form.add_error(None, "Error creating your User")
	else:
		form = RegisterForm()
	return render(request, 'project/register.html', {'form':form})

mysite/project/templates/master.html
<!DOCTYPE html>

{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'project/css/bootstrap.min.css' %}" />
    {% block references %}{% endblock %}
    <title>{% block title %}{% endblock %} - Skydive Coaching</title>

</head>
<body>
	<div class="navbar navbar-inverse navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a>Skydive Coaching</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a href="{% url 'project:Home' %}">Home</a></li>
					{% if user.username %}
					<li><a href="{% url 'project:Jumps' %}">Jumps</a></li>
					{% endif %}
					<li><a>Skills</a></li>
					<li><a>Contact</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					{% if user.username %}
					<li><a href="{% url 'project:UserProfile' user.userprofile.id %}">{{ user.username }}</a></li>
					<li><a href="{% url 'project:Logout' %}">Logout</a></li>
					{% else %}
					<li><a href="{% url 'project:Login' %}">Login</a></li>
					<li><a href="{% url 'project:Register' %}">Register</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</div>
    <div class="container">
        {% block content %}{% endblock %}
        <hr />
        <footer>
        	<p>&copy; {% now "Y" %} - Sam Doughty</p>
        </footer>
    </div>
</body>

{% block jquery %}{% endblock %}
</html>

mysite/project/templates/project/index.html
{% extends "master.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
	<div class="col-lg-8">
		<br />
		<iframe src="//player.vimeo.com/video/96571020?color=0000AA" width="700" height="394" frameborder="0"></iframe>
	</div>

	<div class="col-lg-4">
		<h3> About Skydive Coaching Website</h3>

		<p>
			This website was designed to help make it easier for new Skydivers to find information about Coaching, find Coaches and progress quickly.
			The aim is to provide a central location for videos, feedback and general tips that can help any student.
			It also allows coaches to better understand your flying ability before any jumps, meaning that their coaching can be more tailored to you.
			Finally with the signup system, we can provide information to students, coaches and dropzones about who is available.
			Hopefully restricting the number of days with students stuck on the groud not jumping as they don't have a coach and allowing people to experience a vast number of disciplines.
		</p>
	</div>
</div>
{% endblock %}

mysite/project/templates/project/jump.html
{% extends "master.html" %}

{% block references %}
<script type="text/javascript">

function SaveContent() {
	console.log("create post is working!") // sanity check
    $.ajax({
        url : "edit/{{ jump.id}}", // the endpoint
        type : "POST", // http method
        data : { Description : $('#post-description').html() , Notes : $('#post-notes').html() }, // data sent with the post request

        // handle a successful response
        success : function(json) {
            $('#post-text').val(''); // remove the value from the input
            console.log(json); // log the returned json to the console
            console.log("success"); // another sanity check
            $('#ErrorMessage').html("Save successful.")
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            $('#ErrorMessage').html("Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a>"); // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
};

</script>
{% endblock %}

{% block title %}{{ jump.ShortDescription }}{% endblock %}

{% block content %}
<div class="container">
	<dl>
		<dt>Short Description</dt>
		<dd>{{ jump.ShortDescription }}</dd>
	</dl>
	<dl>
		<dt>Jump Date</dt>
		<dd>{{ jump.JumpDate }}</dd>
	</dl>
	<dl>
		<dt>Jump Type</dt>
		<dd>{{ jump.JumpTypeID.JumpTypeName }}</dd>
	</dl>
	<dl>
		<dt>Video</dt>
		<dd>
			<iframe src="//www.youtube.com/embed/{{ jump.VideoResourceID.URL }}" width="500" height="284" frameborder="0" class="youtube-player" type="text/html"></iframe>
		</dd>
	</dl>
	<dl>
		<dt>Jump Description</dt>
		<dd>
			<div id="post-description" contenteditable=true>
				{{ jump.TheDescription }}
			</div>
		</dd>
	</dl>
	<dl>
		<dt>Notes</dt>
		<dd>
			<div id="post-notes" contenteditable=true>
				{{ jump.Notes }}
			</div>
		</dd>
	</dl>
	<dl>
		<dt></dt>
		<dd>
			<div id="ErrorMessage" style="color:red"></div>
		</dd>
	<a href="javascript:void(0)" onclick="SaveContent()">Save Content</a>
</div>
{% endblock %}

{% block jquery %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript">
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');
 
/*
The functions below will create a header with csrftoken
*/
 
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
function sameOrigin(url) {
    // test that a given url is a same-origin URL
    // url could be relative or scheme relative or absolute
    var host = document.location.host; // host + port
    var protocol = document.location.protocol;
    var sr_origin = '//' + host;
    var origin = protocol + sr_origin;
    // Allow absolute or scheme relative URLs to same origin
    return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
        (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
        // or any other URL that isn't scheme relative or absolute i.e relative.
        !(/^(\/\/|http:|https:).*/.test(url));
}
 
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
            // Send the token to same-origin, relative URLs only.
            // Send the token only if the method warrants CSRF protection
            // Using the CSRFToken value acquired earlier
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});</script>
{% endblock %}

mysite/project/templates/project/jumps.html
{% extends "master.html" %}

{% load staticfiles %}

{% block references %}
{{block.super}}
<link rel="stylesheet" href="{% static 'project/css/carousel.css' %}" />
{% endblock %}

{% block title %}Jumps{% endblock %}

{% block content %}
<div class="container marketing">
	{% for item in jumps %}
	<div class="row featurette">
		<div class="col-md-7">
			<h2 class="featurette-heading"><a href="{% url 'project:Jump' item.id %}">{{ item.ShortDescription }}</a></h2>
			<p class="lead">
				{{ item.TheDescription }}
			</p>
		</div>
		<div class="col-md-5">
			{% if item.VideoResourceID %}
			<img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" 
			src="http://img.youtube.com/vi/{{ item.VideoResourceID.URL }}/0.jpg" data-holder-rendered="true">
			{% else %}
			<img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjE5MC4zMTI1IiB5PSIyNTAiIHN0eWxlPSJmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjNwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj41MDB4NTAwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true">
			{% endif %}
		</div>
	</div>
	{% if not forloop.last %}
	<hr class="featurette-divider">
	{% endif %}
	{% endfor %}
</div>
{% endblock %}

mysite/project/templates/project/login.html
{% extends "master.html" %}

{% load staticfiles %}

{% block references %}
{{block.super}}
<link rel="stylesheet" href="{% static 'project/css/signin.css' %}" />
{% endblock %}

{% block title %}Login{% endblock %}

{% block content %}
<form action="{% url 'project:Login' %}" class="form-signin" method="post">
	{% csrf_token %}

	<h2 class="form-signin-header">Please sign in</h2>
	<input type="text" class="form-control" placeholder="Username" name="{{ form.username.html_name }}" >
	<input type="password" class="form-control" placeholder="Password" name="{{ form.password.html_name }}">
	<div class="checkbox">
		<label>
			<input type="checkbox" value="remember-me" name="{{ form.remember.html_name }}">Remember me
		</label>
	</div>
	<button type="submit" class="btn btn-lg btn-primary btn-block">Login</button>
</form>

{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
    </div>
{% endfor %}
{{ form.non_field_errors }}
{% endblock %}

mysite/project/templates/project/register.html
{% extends "master.html" %}

{% load staticfiles %}

{% block references %}
{{block.super}}
<link rel="stylesheet" href="{% static 'project/css/register.css' %}" />
{% endblock %}

{% block title %}Register{% endblock %}

{% block content %}
<form action="{% url 'project:Register' %}" class="form-register" method="post">
	{% csrf_token %}

	<h2 class="form-register-header">Register</h2>
	<input type="text" class="form-control" placeholder="Username" name="{{ form.username.html_name }}" autocomplete="off">
	<input type="password" class="form-control" placeholder="Password" name="{{ form.password.html_name }}" autocomplete="off">
	<input type="text" class="form-control" placeholder="First Name" name = "{{ form.firstname.html_name }}">
	<input type="text" class="form-control" placeholder="Last Name" name = "{{ form.lastname.html_name }}">
	<input type="email" class="form-control" placeholder="Email" name = "{{ form.email.html_name }}">
	<input type="number" class="form-control" placeholder="Jump Number" name="{{ form.jumpnumber.html_name }}">
	<button type="submit" class="btn btn-lg btn-primary btn-block">Register</button>
</form>

{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
    </div>
{% endfor %}
{{ form.non_field_errors }}
{% endblock %}

mysite/project/templates/project/user.html
{% extends "master.html" %}

{% block title %}{% endblock %}

{% block content %}
<div class="container">
	<dl>
		<dt>Username</dt>
		<dd>{{ userprofile.UserID.username }}</dd>
	</dl>
	<dl>
		<dt>First Name</dt>
		<dd>{{ userprofile.UserID.first_name }}</dd>
	</dl>
	<dl>
		<dt>Last Name</dt>
		<dd>{{ userprofile.UserID.last_name }}</dd>
	</dl>
	<dl>
		<dt>Email</dt>
		<dd>{{ userprofile.UserID.email }}</dd>
	</dl>
	<dl>
		<dt>Jump Number</dt>
		<dd>{{ userprofile.JumpNumber }}</dd>
	</dl>
	<dl>
		<dt>Active</dt>
		<dd>{{ userprofile.UserID.is_active }}<dd>
	</dl>
</div>
{% endblock %}